apiVersion: v1
kind: Secret
metadata:
  name: shadowml-secrets
  namespace: shadowml
type: Opaque
stringData:
  database-url: postgresql+asyncpg://postgres:password@postgres-svc:5432/shadowml
  postgres-password: password