FROM python:3.11-slim
WORKDIR /app
COPY models/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY models/model_v2/ .
EXPOSE 8002
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8002", "--workers", "1"]
